### PR TITLE
Add support for Go 1.8

### PR DESCRIPTION
**Pull request by jtescher**

### CODE REVIEW

**Comment by Fale** [comment]
any update on this?

**Comment by jasonmccallister** [comment]
Would love to see an update on this, I am trying OpenShift online and need a Go image for deployment, not having Go 1.8 (the context package specifically and yes I know it is in the experimental package in 1.7) is somewhat of a buzz kill.

Anything we can do to move this along? Does it need documentation or other changes?

**Comment by liam-middlebrook** [comment]
Ping, this is something that would be pretty useful to have available!

**Comment by bigg01** [comment]
I need that too. Prometheus need 1.8

**Comment by 0xmichalis** [comment]
https://github.com/sclorg/golang-container is a better maintaned repo with support for 1.8. Please use that instead, this repo is not maintained anymore.

**Pull request closed without merging**
